version: "3.9"

services:
  api:
    build: .
    container_name: tri-demandes-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      GCP_PROJECT_ID: tri-demandes-clients
      GCS_BUCKET_NAME: clean_complaints
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/tri-demandes-clients-da1709669c29.json
    volumes:
      - ./secrets/tri-demandes-clients-da1709669c29.json:/secrets/tri-demandes-clients-da1709669c29.json:ro
    restart: unless-stopped